/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import Logic.*;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 * @author Batool Isa, Fatima Mahfoodh, Fedaa Abdualwahab, Fatema Omran
 * @version 1.0
 * @created 10-May-2023 11:34:54 AM
 */
public class AssignMemberToPT extends javax.swing.JFrame {

    ArrayList<Employee> ptList = GymSystem.getEmployeesList();
    Member tempMember;
    MembersOptions membersOptions;

    /**
     * Name: AssignMemberToPT Purpose/description: default constructors that
     * used to initialize the form components.
     */
    public AssignMemberToPT() {
        initComponents();
    }
    /**
     * Name: AssignMemberToPT
     * Purpose/description: custom constructors that used
     * to initialize an object using value passed as arguments
     *
     * @param tempMember variable that holds Member object
     * @param membersOptions variable that holds membersOptions object
     */
    public AssignMemberToPT(Member tempMember, MembersOptions membersOptions) {
        this.tempMember = tempMember;
        this.membersOptions = membersOptions;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        assginMemToPT = new javax.swing.JLabel();
        assignBtn = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        lblDumbbellImg = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblBPLogo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        ptId1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(57, 72, 103));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assginMemToPT.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        assginMemToPT.setForeground(new java.awt.Color(156, 176, 219));
        assginMemToPT.setText("Assign a personal Trainer to a Member");
        jPanel1.add(assginMemToPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        assignBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assignBtn.setText("Assign");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        jPanel1.add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 120, 40));

        lblTitle1.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("GYM ADMINISTRATION ");
        jPanel1.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        lblDumbbellImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/dumbbellsmall.png"))); // NOI18N
        jPanel1.add(lblDumbbellImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 40));

        lblTitle2.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("SYSTEM");
        jPanel1.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        lblBPLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/BPLogosmall.png"))); // NOI18N
        jPanel1.add(lblBPLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 230, 30));

        ptId1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ptId1.setForeground(new java.awt.Color(255, 255, 255));
        ptId1.setText("Choose Personal Trainer:");
        jPanel1.add(ptId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Invoked when AssignMemberToPT form is opened. IT initialize the comboBox
     * with Personal Trainer's list
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            for (int i = 0; i < ptList.size(); i++) {
                if (ptList.get(i) instanceof PersonalTrainer) {
                    String pt = ptList.get(i).toString();
                    jComboBox1.addItem(pt);
                }

            }
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "The following Exception occures: \n"
                    + ex, "Error!!", 0);
        } catch (Exception ex2) {
            JOptionPane.showMessageDialog(this, "The following Exception occures: \n"
                    + ex2, "Error!!", 0);
        }

    }//GEN-LAST:event_formWindowOpened
    /**
     * Invoked when Assign button is clicked. It assign the Member to the selected Personal Trainer
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        try {
            for (int i = 0; i < ptList.size(); i++) {
                String pt = ptList.get(i).toString();
                if (pt.equals(jComboBox1.getSelectedItem())) {
                    GymSystem.assignPtToMember(tempMember.getMembershipID(), ptList.get(i).getEmployeeID());
                    JOptionPane.showMessageDialog(this, "The Member has been assigned to a Personal Trainer successfully", "Member assigned", 1);
                    this.dispose();
                    membersOptions.setVisible(true);
                }
            }
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "The following Exception occures: \n"
                    + ex, "Error!!", 0);
        } catch (Exception ex2) {
            JOptionPane.showMessageDialog(this, "The following Exception occures: \n"
                    + ex2, "Error!!", 0);
        }


    }//GEN-LAST:event_assignBtnActionPerformed
        /**
     * Invoked when Back button is clicked. It closes AssginMemberToPT frame and shows membersOptions screen 
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        membersOptions.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignMemberToPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignMemberToPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignMemberToPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignMemberToPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignMemberToPT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assginMemToPT;
    private javax.swing.JButton assignBtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBPLogo;
    private javax.swing.JLabel lblDumbbellImg;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel ptId1;
    // End of variables declaration//GEN-END:variables
}
