/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import Logic.*;
import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 * @author Batool Isa, Fatima Mahfoodh, Fedaa Abdualwahab, Fatema Omran
 * @version 1.0
 * @created 10-May-2023 11:34:54 AM
 */
public class EmployeesOptions extends javax.swing.JFrame {

    MainMenu mainMenu;

    /**
     * Name: EmployeesOptions Purpose/description: custom constructors that used
     * to initialize an object using value passed as arguments
     *
     * @param mainMenu variable that holds MainMenu object
     */
    public EmployeesOptions(MainMenu mainMenu) {
        this.mainMenu = mainMenu;
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }
    /**
     * Name: EmployeesOptions Purpose/description: default constructors that
     * used to initialize the form components.
     */
    public EmployeesOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        btnAddEmp = new javax.swing.JButton();
        btnViewEmp = new javax.swing.JButton();
        btnUpdateEmp = new javax.swing.JButton();
        btnDeleteEmp = new javax.swing.JButton();
        btnGenerateReport = new javax.swing.JButton();
        btnViewPTList = new javax.swing.JButton();
        lblBPLogo = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblDumbbellImg = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackground.setBackground(new java.awt.Color(57, 72, 103));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddEmp.setBackground(new java.awt.Color(241, 246, 249));
        btnAddEmp.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnAddEmp.setText("Add New Employee");
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });
        pnlBackground.add(btnAddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 395, 44));

        btnViewEmp.setBackground(new java.awt.Color(241, 246, 249));
        btnViewEmp.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnViewEmp.setText("View Employee Information");
        btnViewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmpActionPerformed(evt);
            }
        });
        pnlBackground.add(btnViewEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 395, 44));

        btnUpdateEmp.setBackground(new java.awt.Color(241, 246, 249));
        btnUpdateEmp.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnUpdateEmp.setText("Update Employee Information");
        btnUpdateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEmpActionPerformed(evt);
            }
        });
        pnlBackground.add(btnUpdateEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 395, 44));

        btnDeleteEmp.setBackground(new java.awt.Color(241, 246, 249));
        btnDeleteEmp.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnDeleteEmp.setText("Delete Employee");
        btnDeleteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmpActionPerformed(evt);
            }
        });
        pnlBackground.add(btnDeleteEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 395, 44));

        btnGenerateReport.setBackground(new java.awt.Color(241, 246, 249));
        btnGenerateReport.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnGenerateReport.setText("Generate Marketing Report");
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });
        pnlBackground.add(btnGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, 395, 44));

        btnViewPTList.setBackground(new java.awt.Color(241, 246, 249));
        btnViewPTList.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnViewPTList.setText("View Personal Trainer's Members List");
        btnViewPTList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPTListActionPerformed(evt);
            }
        });
        pnlBackground.add(btnViewPTList, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 395, 44));

        lblBPLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/BPLogosmall.png"))); // NOI18N
        pnlBackground.add(lblBPLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("GYM ADMINISTRATION ");
        pnlBackground.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        lblTitle2.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("SYSTEM");
        pnlBackground.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        lblDumbbellImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/dumbbellsmall.png"))); // NOI18N
        pnlBackground.add(lblDumbbellImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 40));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlBackground.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 40, 60, -1));

        btnExit.setBackground(new java.awt.Color(204, 204, 204));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlBackground.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 80, 60, -1));

        getContentPane().add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Invoked when Generate Report button is clicked. It calls generateMarketingReport method from GymSystem Class in Logic package which will 
     * create a text file in Project Directory.
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        GymSystem.generateMarketingReport();
        JOptionPane.showMessageDialog(this, "The Report has been generated sucessfully", "Report Generated", 1);
    }//GEN-LAST:event_btnGenerateReportActionPerformed
    /**
     * Invoked when Update employee information button is clicked. The method prompt the user to choose the Employee Id.
     * It then closes EmployeesOptions form and shows UpdateEmployeeInformation form.
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void btnUpdateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEmpActionPerformed
        JComboBox cb = new JComboBox();
        ArrayList<Employee> empList = GymSystem.getEmployeesList();
        for (Employee emp : empList) {
            cb.addItem(emp.getEmployeeID());
        }
        int choice = JOptionPane.showConfirmDialog(this, cb, "Select Employee ID", JOptionPane.OK_CANCEL_OPTION);
        if (choice == JOptionPane.CANCEL_OPTION || choice == JOptionPane.CLOSED_OPTION  ) {// if clicked cancel
            this.setVisible(true);
        } else {
            int empID = (int) cb.getSelectedItem();
            Employee tempEmp = GymSystem.searchForEmployee(empID);
            if (tempEmp == null) {
                JOptionPane.showMessageDialog(this, "The Employee Does Not Exist", "Error Message", 2);
            } else {
                UpdateEmployeeInformation updateEmpInfo = new UpdateEmployeeInformation(this, tempEmp);
                updateEmpInfo.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnUpdateEmpActionPerformed
    /**
     * Invoked when Add new Employee button is clicked. The method closes EmployeesOptions form and displays EmployeeRegistration form.
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        this.setVisible(false);
        EmployeeRegistrationForm empForm = new EmployeeRegistrationForm(this);
        empForm.setVisible(true);
    }//GEN-LAST:event_btnAddEmpActionPerformed
    /**
     * Invoked when Delete Employee button is clicked. The method prompts the user to choose the Employee ID
     * and then calls deleteEmployee method from GymSystem Class in Logic package
     * 
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void btnDeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmpActionPerformed
        JComboBox cb = new JComboBox();
        ArrayList<Employee> empList = GymSystem.getEmployeesList();
        for (Employee emp : empList) {
            cb.addItem(emp.getEmployeeID());
        }
        int choice = JOptionPane.showConfirmDialog(this, cb, "Select Employee ID", JOptionPane.OK_CANCEL_OPTION);
        if ( choice == JOptionPane.CANCEL_OPTION || choice == JOptionPane.CLOSED_OPTION  ) {// if clicked cancel
            this.setVisible(true);
        } else {
            Integer empID = (Integer) cb.getSelectedItem();
            if(empID != null){
                Employee tempEmp = GymSystem.searchForEmployee(empID);
                String[] options = {"Yes", "Cancel"};
                int choice2 = JOptionPane.showOptionDialog(this, "Are you sure you want to delete the employee?", "Confirmation Message!", 0, JOptionPane.WARNING_MESSAGE, null, options, null);

                if (choice2 == 0) {
                    GymSystem.deleteEmployee(empID);
                    JOptionPane.showMessageDialog(this, "The Employee information has been deleted", "Employee information deleted", 1);
                } else if (choice2 == 1) {//remove (cancel button)
                    this.setVisible(true);
                }
            }
            
            
        }
    }//GEN-LAST:event_btnDeleteEmpActionPerformed
    /**
     * Invoked when View Employee Information button is clicked. The method prompts the user to choose the Employee ID
     * and then closes EmployeesOptions form and displays EmployeeInforamtion form.
     * 
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void btnViewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmpActionPerformed
        JComboBox cb = new JComboBox();
        ArrayList<Employee> empList = GymSystem.getEmployeesList();
        for (Employee emp : empList) {
            cb.addItem(emp.getEmployeeID());
        }
        int choice = JOptionPane.showConfirmDialog(this, cb, "Select Employee ID", JOptionPane.OK_CANCEL_OPTION);
        if (choice == JOptionPane.CANCEL_OPTION || choice == JOptionPane.CLOSED_OPTION ) {// if clicked cancel
            this.setVisible(true);
        } else {
            Integer empID = (Integer) cb.getSelectedItem();
            if(empID != null){
                Employee tempEmp = GymSystem.searchForEmployee(empID);
                EmployeeInformation empInfo = new EmployeeInformation(this, tempEmp);
                empInfo.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnViewEmpActionPerformed
    /**
     * Invoked when View Personal Trainer's Member List button is clicked. The method prompts the user to choose the Personal Trainer ID
     * and then closes EmployeesOptions form and displays ViewPTMembersList form.
     * 
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void btnViewPTListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPTListActionPerformed
        JComboBox cb = new JComboBox();
        ArrayList<Employee> empList = GymSystem.getEmployeesList();
        for (Employee emp : empList) {
            if (emp instanceof PersonalTrainer)
            cb.addItem(emp.getEmployeeID());
        }
        int choice = JOptionPane.showConfirmDialog(this, cb, "Select Employee ID", JOptionPane.OK_CANCEL_OPTION);
        if (choice == JOptionPane.CANCEL_OPTION) {// if clicked cancel
            this.setVisible(true);
        } else {
            Integer empID = (Integer) cb.getSelectedItem();
            if(empID != null){
                Employee tempEmp = GymSystem.searchForEmployee(empID);
                this.setVisible(false);
                ViewPTMembersList ptList = new ViewPTMembersList((PersonalTrainer) tempEmp, this);
                ptList.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnViewPTListActionPerformed
    /**
     * Invoked when Back button is clicked. It closes EmployeesOptions frame and
     * shows Main Menu frame
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed
    /**
     * Invoked when Exit button is clicked. It shutdowns the program
     * 
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeesOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeesOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeesOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeesOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeesOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteEmp;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnUpdateEmp;
    private javax.swing.JButton btnViewEmp;
    private javax.swing.JButton btnViewPTList;
    private javax.swing.JLabel lblBPLogo;
    private javax.swing.JLabel lblDumbbellImg;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
