/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import Logic.*;
import javax.swing.JOptionPane;
/**
 * @author Batool Isa, Fatima Mahfoodh, Fedaa Abdualwahab, Fatema Omran
 * @version 1.0
 * @created 10-May-2023 11:34:54 AM
 */
public class EmployeeRegistrationForm extends javax.swing.JFrame {

    EmployeesOptions empListScreen;

      /**
     * Name: EmployeeRegistrationForm Purpose/description: custom constructors that used
     * to initialize an object using value passed as arguments
     *
     * @param empListScreen variable that holds employeesOptions object
     */
    public EmployeeRegistrationForm(EmployeesOptions empListScreen) {
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
        this.empListScreen = empListScreen;

    }
    /**
     * Name: EmployeeRegistrationForm Purpose/description: default constructors that
     * used to initialize the form components.
     */
    public EmployeeRegistrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupGenderERF = new javax.swing.ButtonGroup();
        GroupPositionERF = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblEmployeeRFTitle = new javax.swing.JLabel();
        btnERFSubmit = new javax.swing.JButton();
        lblBPLogo = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblDumbbellImg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblERFSurname = new javax.swing.JLabel();
        lblERFAddress = new javax.swing.JLabel();
        txtERFAddress = new javax.swing.JTextField();
        lblERFPosition = new javax.swing.JLabel();
        jRBtnERFPersonalTrainer = new javax.swing.JRadioButton();
        jRBtnERFOthers = new javax.swing.JRadioButton();
        txtERFSurname = new javax.swing.JTextField();
        lblLnameError1 = new javax.swing.JLabel();
        lblAddressError = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblERFFirstName = new javax.swing.JLabel();
        lblERFPhone = new javax.swing.JLabel();
        txtERFSalary = new javax.swing.JTextField();
        lblERFSalary = new javax.swing.JLabel();
        txtERFPhone = new javax.swing.JTextField();
        txtERFFirstName = new javax.swing.JTextField();
        lblFnameError = new javax.swing.JLabel();
        lblPhoneError = new javax.swing.JLabel();
        lblSalaryError = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(57, 72, 103));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmployeeRFTitle.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblEmployeeRFTitle.setForeground(new java.awt.Color(156, 176, 219));
        lblEmployeeRFTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmployeeRFTitle.setText("Employee Registration Form");
        jPanel1.add(lblEmployeeRFTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        btnERFSubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnERFSubmit.setText("Submit");
        btnERFSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnERFSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnERFSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, -1, -1));

        lblBPLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/BPLogosmall.png"))); // NOI18N
        jPanel1.add(lblBPLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("GYM ADMINISTRATION ");
        jPanel1.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        lblTitle2.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("SYSTEM");
        jPanel1.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        lblDumbbellImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/dumbbellsmall.png"))); // NOI18N
        jPanel1.add(lblDumbbellImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 40));

        jPanel2.setBackground(new java.awt.Color(57, 72, 103));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblERFSurname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblERFSurname.setForeground(new java.awt.Color(255, 255, 255));
        lblERFSurname.setText("Surname:");
        jPanel2.add(lblERFSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        lblERFAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblERFAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblERFAddress.setText("Address:");
        jPanel2.add(lblERFAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 100, -1));
        jPanel2.add(txtERFAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, 30));

        lblERFPosition.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblERFPosition.setForeground(new java.awt.Color(255, 255, 255));
        lblERFPosition.setText("Position:");
        jPanel2.add(lblERFPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 100, 30));

        GroupPositionERF.add(jRBtnERFPersonalTrainer);
        jRBtnERFPersonalTrainer.setForeground(new java.awt.Color(255, 255, 255));
        jRBtnERFPersonalTrainer.setText("Personal Trainer");
        jPanel2.add(jRBtnERFPersonalTrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 160, -1));

        GroupPositionERF.add(jRBtnERFOthers);
        jRBtnERFOthers.setForeground(new java.awt.Color(255, 255, 255));
        jRBtnERFOthers.setText("Regular Employee");
        jPanel2.add(jRBtnERFOthers, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 160, -1));
        jPanel2.add(txtERFSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 160, 30));

        lblLnameError1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblLnameError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 30));

        lblAddressError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblAddressError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 260, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 490, 280));

        jPanel3.setBackground(new java.awt.Color(57, 72, 103));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblERFFirstName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblERFFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblERFFirstName.setText("First Name:");
        jPanel3.add(lblERFFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        lblERFPhone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblERFPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblERFPhone.setText("Phone:");
        jPanel3.add(lblERFPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, -1));
        jPanel3.add(txtERFSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 160, 30));

        lblERFSalary.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblERFSalary.setForeground(new java.awt.Color(255, 255, 255));
        lblERFSalary.setText("Salary:");
        jPanel3.add(lblERFSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 58, -1));
        jPanel3.add(txtERFPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, 30));
        jPanel3.add(txtERFFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 160, 30));

        lblFnameError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblFnameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, 30));

        lblPhoneError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblPhoneError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 30));

        lblSalaryError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblSalaryError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 250, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 530, 270));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Invoked when Submit button is clicked. It takes information entered by user and creates Employee object
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void btnERFSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnERFSubmitActionPerformed
        boolean submit = true;
        lblFnameError.setText(null);
        lblLnameError1.setText(null);
        lblAddressError.setText(null);
        lblSalaryError.setText(null);
        lblPhoneError.setText(null);

        if (txtERFFirstName.getText().isEmpty() || txtERFFirstName.getText().length() < 3) {
            lblFnameError.setText("*First name must be at least 3 characters");
            submit = false;
        }
        if (txtERFSurname.getText().isEmpty() || txtERFSurname.getText().length() < 3) {
            lblLnameError1.setText("*Surname must be at least 3 characters");
            submit = false;
        }
        if (txtERFAddress.getText().isEmpty() || txtERFAddress.getText().length() < 6) {
            lblAddressError.setText("*Address must be at least 6 characters");
            submit = false;
        }
        if (txtERFSalary.getText().isEmpty() || txtERFSalary.getText().length() < 3) {
            lblSalaryError.setText("*Salary must be at least 3 characters");
            submit = false;
        }
        if (txtERFPhone.getText().isEmpty() || txtERFPhone.getText().length() < 6) {
            lblPhoneError.setText("*Phone must be at least 6 digits");
            submit = false;
        }
        try {
            if (submit == true) {
                String fName = txtERFFirstName.getText();
                String lName = txtERFSurname.getText();
                String address = txtERFAddress.getText();
                boolean pt = false;
                if (jRBtnERFPersonalTrainer.isSelected()) {
                    pt = true;
                }

                double salary = Double.parseDouble(txtERFSalary.getText());
                int phone = Integer.parseInt(txtERFPhone.getText());
                GymSystem.addEmployee(fName, lName, address, phone, salary, pt);
                JOptionPane.showMessageDialog(this, "The Employee has been added successfully", "Successful Registraion", 1);
                dispose();
                empListScreen.setVisible(true);
            }
        } catch (NumberFormatException ex1) {
            JOptionPane.showMessageDialog(this, "Phone and Salary Inputs must be numbers", "Number Format Exception", 0);
        }

    }//GEN-LAST:event_btnERFSubmitActionPerformed
    /**
     * Invoked when Back button is clicked. It closes EmployeeRegistrationForm frame and
     * shows EmployeesOptions screen
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        empListScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed
    /**
     * Invoked when EmployeeRegistrationForm frame is opened. It sets gender default option to male 
     *
     * @param evt the event that triggered the invocation of this method.
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jRBtnERFOthers.setSelected(true);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupGenderERF;
    private javax.swing.ButtonGroup GroupPositionERF;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnERFSubmit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRBtnERFOthers;
    private javax.swing.JRadioButton jRBtnERFPersonalTrainer;
    private javax.swing.JLabel lblAddressError;
    private javax.swing.JLabel lblBPLogo;
    private javax.swing.JLabel lblDumbbellImg;
    private javax.swing.JLabel lblERFAddress;
    private javax.swing.JLabel lblERFFirstName;
    private javax.swing.JLabel lblERFPhone;
    private javax.swing.JLabel lblERFPosition;
    private javax.swing.JLabel lblERFSalary;
    private javax.swing.JLabel lblERFSurname;
    private javax.swing.JLabel lblEmployeeRFTitle;
    private javax.swing.JLabel lblFnameError;
    private javax.swing.JLabel lblLnameError1;
    private javax.swing.JLabel lblPhoneError;
    private javax.swing.JLabel lblSalaryError;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JTextField txtERFAddress;
    private javax.swing.JTextField txtERFFirstName;
    private javax.swing.JTextField txtERFPhone;
    private javax.swing.JTextField txtERFSalary;
    private javax.swing.JTextField txtERFSurname;
    // End of variables declaration//GEN-END:variables
}
