/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import Logic.*;

/**
 * @author Batool Isa, Fatima Mahfoodh, Fedaa Abdualwahab, Fatema Omran
 * @version 1.0
 * @created 10-May-2023 11:34:54 AM
 
 * A class which displays the main menu screen of the BP gym
 * system and it displays two options to choose; either gym employees or gym
 * members and based on user's choice a proper form will appear to the user;
 * either MembersOptions or EmployeesOptions.
 */
public class MainMenu extends javax.swing.JFrame {
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        btnGymMembers = new javax.swing.JButton();
        btnGymEmployees = new javax.swing.JButton();
        lblMainMenuImg = new javax.swing.JLabel();
        lblBPLogo = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblDumbbellImg = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 703));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackground.setBackground(new java.awt.Color(57, 72, 103));
        pnlBackground.setMaximumSize(new java.awt.Dimension(1340, 640));
        pnlBackground.setMinimumSize(new java.awt.Dimension(1340, 640));
        pnlBackground.setPreferredSize(new java.awt.Dimension(1340, 640));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGymMembers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGymMembers.setText("Gym Members");
        btnGymMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGymMembersActionPerformed(evt);
            }
        });
        pnlBackground.add(btnGymMembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 160, 70));

        btnGymEmployees.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGymEmployees.setText("Gym Employees");
        btnGymEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGymEmployeesActionPerformed(evt);
            }
        });
        pnlBackground.add(btnGymEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 160, 70));

        lblMainMenuImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/MainMenu.png"))); // NOI18N
        pnlBackground.add(lblMainMenuImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1360, 470));

        lblBPLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/BPLogosmall.png"))); // NOI18N
        pnlBackground.add(lblBPLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("GYM ADMINISTRATION ");
        pnlBackground.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        lblTitle2.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("SYSTEM");
        pnlBackground.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        lblDumbbellImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/dumbbellsmall.png"))); // NOI18N
        pnlBackground.add(lblDumbbellImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 40));

        btnExit.setBackground(new java.awt.Color(204, 204, 204));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlBackground.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 30, 60, -1));

        getContentPane().add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Name: btnGymEmployeesActionPerformed
     * Purpose/description: to close the MainMenu form and to create an object
     * of EmployeesOptions to display EmployeesOptions form.
     * @param evt - An event object represents the action of clicking on gym 
     * employees button.
     */
    
    private void btnGymEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGymEmployeesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        EmployeesOptions  emplist = new EmployeesOptions(this);
        emplist.setVisible(true);     
    }//GEN-LAST:event_btnGymEmployeesActionPerformed

    /**
     * Name: btnGymMembersActionPerformed
     * Purpose/description: to close the MainMenu form and to create an object
     * of MembersOptions to display MembersOptions form.
     * @param evt An event object represents the action of clicking on gym 
     * members button.
     */
    private void btnGymMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGymMembersActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MembersOptions  memlist = new MembersOptions(this);
        memlist.setVisible(true);      
    }//GEN-LAST:event_btnGymMembersActionPerformed
    
     /**
     * Name: btnExitActionPerformed
     * Purpose/description: to exit the system/program  
     * @param evt An event object represents the action of clicking on  
     * exit button.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGymEmployees;
    private javax.swing.JButton btnGymMembers;
    private javax.swing.JLabel lblBPLogo;
    private javax.swing.JLabel lblDumbbellImg;
    private javax.swing.JLabel lblMainMenuImg;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
