/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import Logic.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Batool Isa, Fatima Mahfoodh, Fedaa Abdualwahab, Fatema Omran
 * @version 1.0
 * @created 10-May-2023 11:34:54 AM
 * A class to add a new student member to the BP gym system
 */
public class MemberRegistrationFormStudent extends javax.swing.JFrame {

    MembersOptions memberOption2;
    MemberType memberType1;

    /**
     * Creates new form MemberRegistrationFormStudent
     */
    public MemberRegistrationFormStudent(MemberType memberType1, MembersOptions memberOption2) {
        this.memberType1 = memberType1;
        this.memberOption2 = memberOption2;
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);

    }

    public MemberRegistrationFormStudent() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupGenderStudentMRF1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblStudentMRFStudent = new javax.swing.JLabel();
        lblStudentMRFTitle = new javax.swing.JLabel();
        btnStudentMRFSubmit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblStudentMRFFirstName = new javax.swing.JLabel();
        lblStudentMRFPhone = new javax.swing.JLabel();
        txtStudentMRFPhone = new javax.swing.JTextField();
        lblStudentMRFDeptNo = new javax.swing.JLabel();
        txtStudentMRFTeam = new javax.swing.JTextField();
        btnStudentMRFMale = new javax.swing.JRadioButton();
        btnStudentMRFFemale = new javax.swing.JRadioButton();
        lblStudentMRFGender = new javax.swing.JLabel();
        txtStudentMRFFirstName = new javax.swing.JTextField();
        lblFnameError = new javax.swing.JLabel();
        lblPhoneError = new javax.swing.JLabel();
        lblTeamError = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblStudentMRFSurname = new javax.swing.JLabel();
        lblStudentMRFAddress = new javax.swing.JLabel();
        txtStudentMRFAddress = new javax.swing.JTextField();
        lblStudentMRFDOB = new javax.swing.JLabel();
        jDateChooserStudentMRF = new com.toedter.calendar.JDateChooser();
        lblStudentMRFPosition = new javax.swing.JLabel();
        jComboBoxStudentMRF = new javax.swing.JComboBox<>();
        txtStudentMRFSurname = new javax.swing.JTextField();
        lblLnameError = new javax.swing.JLabel();
        lblAddressError = new javax.swing.JLabel();
        lblDateError = new javax.swing.JLabel();
        lblBPLogo = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblDumbbellImg = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(57, 72, 103));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStudentMRFStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStudentMRFStudent.setForeground(new java.awt.Color(179, 190, 194));
        lblStudentMRFStudent.setText("STUDENT");
        jPanel1.add(lblStudentMRFStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, -1, -1));

        lblStudentMRFTitle.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblStudentMRFTitle.setForeground(new java.awt.Color(156, 176, 219));
        lblStudentMRFTitle.setText("Member Registration Form");
        jPanel1.add(lblStudentMRFTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        btnStudentMRFSubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnStudentMRFSubmit.setText("Submit");
        btnStudentMRFSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentMRFSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudentMRFSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, -1, -1));

        jPanel2.setBackground(new java.awt.Color(57, 72, 103));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStudentMRFFirstName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStudentMRFFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentMRFFirstName.setText("First Name:");
        jPanel2.add(lblStudentMRFFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 115, -1));

        lblStudentMRFPhone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStudentMRFPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentMRFPhone.setText("Phone:");
        jPanel2.add(lblStudentMRFPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 67, -1));
        jPanel2.add(txtStudentMRFPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, 30));

        lblStudentMRFDeptNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStudentMRFDeptNo.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentMRFDeptNo.setText("Team:");
        jPanel2.add(lblStudentMRFDeptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 78, -1));
        jPanel2.add(txtStudentMRFTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 160, 30));

        GroupGenderStudentMRF1.add(btnStudentMRFMale);
        btnStudentMRFMale.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentMRFMale.setText("Male");
        jPanel2.add(btnStudentMRFMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 98, 20));

        GroupGenderStudentMRF1.add(btnStudentMRFFemale);
        btnStudentMRFFemale.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentMRFFemale.setText("Female");
        jPanel2.add(btnStudentMRFFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 98, -1));

        lblStudentMRFGender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStudentMRFGender.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentMRFGender.setText("Gender:");
        jPanel2.add(lblStudentMRFGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));
        jPanel2.add(txtStudentMRFFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 160, 30));

        lblFnameError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblFnameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, 30));

        lblPhoneError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblPhoneError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 30));

        lblTeamError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblTeamError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 340, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 360, 270));

        jPanel3.setBackground(new java.awt.Color(57, 72, 103));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStudentMRFSurname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStudentMRFSurname.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentMRFSurname.setText("Surname:");
        jPanel3.add(lblStudentMRFSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 102, -1));

        lblStudentMRFAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStudentMRFAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentMRFAddress.setText("Address:");
        jPanel3.add(lblStudentMRFAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, 85, -1));
        jPanel3.add(txtStudentMRFAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 69, 160, 30));

        lblStudentMRFDOB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStudentMRFDOB.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentMRFDOB.setText("Date of birth:");
        jPanel3.add(lblStudentMRFDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 128, -1, 30));
        jPanel3.add(jDateChooserStudentMRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 128, 160, 30));

        lblStudentMRFPosition.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStudentMRFPosition.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentMRFPosition.setText("Major:");
        jPanel3.add(lblStudentMRFPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 191, 68, -1));

        jComboBoxStudentMRF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxStudentMRF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT", "Logistics", "Business", "Web media", "Engineering", "Visual design", "Digital marketing", "Film & Animation" }));
        jPanel3.add(jComboBoxStudentMRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 191, 160, 30));
        jPanel3.add(txtStudentMRFSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 6, 160, 30));

        lblLnameError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblLnameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, 30));

        lblAddressError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblAddressError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 30));

        lblDateError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblDateError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 470, 300));

        lblBPLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/BPLogosmall.png"))); // NOI18N
        jPanel1.add(lblBPLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("GYM ADMINISTRATION ");
        jPanel1.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        lblTitle2.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("SYSTEM");
        jPanel1.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        lblDumbbellImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/dumbbellsmall.png"))); // NOI18N
        jPanel1.add(lblDumbbellImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 40));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Name: btnStudentMRFSubmitActionPerformed
     * Purpose/description: to submit a new information of student member to 
     * BP gym system. 
     * @param evt An event object represents the action of clicking on 
     * submit button. 
     */
    private void btnStudentMRFSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentMRFSubmitActionPerformed
        lblFnameError.setText(null);
        lblLnameError.setText(null);
        lblAddressError.setText(null);
        lblTeamError.setText(null);
        lblPhoneError.setText(null);
        lblDateError.setText(null);

        boolean submit = true;

        if (txtStudentMRFFirstName.getText().isEmpty() || txtStudentMRFFirstName.getText().length() < 3) {
            lblFnameError.setText("*First name must be at least 3 characters");
            submit = false;
        }
        if (txtStudentMRFSurname.getText().isEmpty() || txtStudentMRFSurname.getText().length() < 3) {
            lblLnameError.setText("*Surname must be at least 3 characters");
            submit = false;
        }
        if (txtStudentMRFAddress.getText().isEmpty() || txtStudentMRFAddress.getText().length() < 6) {
            lblAddressError.setText("*Address must be at least 6 characters");
            submit = false;
        }
        if (txtStudentMRFTeam.getText().isEmpty() || txtStudentMRFTeam.getText().length() < 5) {
            lblTeamError.setText("*Department Name must be at least 5 characters");
            submit = false;
        }
        if (jDateChooserStudentMRF.getDate() == null) {
            lblDateError.setText("*Date of Birth cannot be null");
            submit = false;
        }
        if (txtStudentMRFPhone.getText().isEmpty() || txtStudentMRFPhone.getText().length() < 6) {
            lblPhoneError.setText("*Phone must be at least 6 digits");
            submit = false;
        }
        try {
            if (submit == true) {
                String fName = txtStudentMRFFirstName.getText();
                String lName = txtStudentMRFSurname.getText();
                String address = txtStudentMRFAddress.getText();
                int phone = Integer.parseInt(txtStudentMRFPhone.getText());
                String team = txtStudentMRFTeam.getText();
                String major = (String) jComboBoxStudentMRF.getSelectedItem();
                // Get the selected date as text

                //String dateOfBirth = jDateChooserStudentMRF.getDateFormatString();
                ///String selectedDate = ((JTextField) dateChooser.getDateEditor().getUiComponent()).getText();
                /// System.out.println("Selected date: " + selectedDate);
                //Date date = jDateChooserStudentMRF.getDate();
                //String dateOfBirth = DateFormat.getDateInstance().format(date);
                SimpleDateFormat sdf = new SimpleDateFormat("d/M/yyyy");
                String dateOfBirth = sdf.format(jDateChooserStudentMRF.getDate());
                String gender = null;
                if (btnStudentMRFMale.isSelected()) {
                    gender = "male";
                } else {
                    gender = "female";
                }
                GymSystem.addStudentMember(fName, lName, address, dateOfBirth, phone, gender, major, team);
                JOptionPane.showMessageDialog(this, "The member has been added successfully", "Successful Registraion", 1);
                dispose();
                memberOption2.setVisible(true);
            }
        } catch (NumberFormatException ex1){
            JOptionPane.showMessageDialog(this, "Phone Input must be number", "Number Format Exception", 0);
        }


    }//GEN-LAST:event_btnStudentMRFSubmitActionPerformed

     /**
     * Name: btnBackActionPerformed
     * Purpose/description: to open MainMenu and close 
     * MemberRegistrationFormStudent. 
     * @param evt - An event object represents the action of clicking on 
     * back button.
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        memberType1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberRegistrationFormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberRegistrationFormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberRegistrationFormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberRegistrationFormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberRegistrationFormStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupGenderStudentMRF1;
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnStudentMRFFemale;
    private javax.swing.JRadioButton btnStudentMRFMale;
    private javax.swing.JButton btnStudentMRFSubmit;
    private javax.swing.JComboBox<String> jComboBoxStudentMRF;
    private com.toedter.calendar.JDateChooser jDateChooserStudentMRF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAddressError;
    private javax.swing.JLabel lblBPLogo;
    private javax.swing.JLabel lblDateError;
    private javax.swing.JLabel lblDumbbellImg;
    private javax.swing.JLabel lblFnameError;
    private javax.swing.JLabel lblLnameError;
    private javax.swing.JLabel lblPhoneError;
    private javax.swing.JLabel lblStudentMRFAddress;
    private javax.swing.JLabel lblStudentMRFDOB;
    private javax.swing.JLabel lblStudentMRFDeptNo;
    private javax.swing.JLabel lblStudentMRFFirstName;
    private javax.swing.JLabel lblStudentMRFGender;
    private javax.swing.JLabel lblStudentMRFPhone;
    private javax.swing.JLabel lblStudentMRFPosition;
    private javax.swing.JLabel lblStudentMRFStudent;
    private javax.swing.JLabel lblStudentMRFSurname;
    private javax.swing.JLabel lblStudentMRFTitle;
    private javax.swing.JLabel lblTeamError;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JTextField txtStudentMRFAddress;
    private javax.swing.JTextField txtStudentMRFFirstName;
    private javax.swing.JTextField txtStudentMRFPhone;
    private javax.swing.JTextField txtStudentMRFSurname;
    private javax.swing.JTextField txtStudentMRFTeam;
    // End of variables declaration//GEN-END:variables
}
