/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import Logic.*;

/**
 *
 * @author Batool Isa, Fatima Mahfoodh, Fedaa Abdualwahab, Fatema Omran
 * @version 1.0
 * @created 10-May-2023 11:34:54 AM 
 * A class which displays a MemberType screen to choose the type of member 
 * to be added to BP gym system; either student or staff and based on user's 
 * choice a proper form will appear to the user to add a new member to the 
 * system.
 */
public class MemberType extends javax.swing.JFrame {

    MembersOptions memberOptions1;

    /**
     * Creates new form MemberType
     */
    public MemberType(MembersOptions memberOptions1) {
        this.memberOptions1 = memberOptions1;
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }

    public MemberType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnStaff = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        lblMainMenuImg = new javax.swing.JLabel();
        lblBPLogo = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblDumbbellImg = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackground.setBackground(new java.awt.Color(57, 72, 103));
        pnlBackground.setMaximumSize(new java.awt.Dimension(1366, 703));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(156, 176, 219));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(156, 176, 219));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Type of Member:");
        pnlBackground.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 350, 50));

        btnStaff.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnStaff.setText("Staff");
        btnStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffActionPerformed(evt);
            }
        });
        pnlBackground.add(btnStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 160, 70));

        btnStudent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnStudent.setText("Student");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });
        pnlBackground.add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 160, 70));

        lblMainMenuImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/MainMenu.png"))); // NOI18N
        pnlBackground.add(lblMainMenuImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1340, 440));

        lblBPLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/BPLogosmall.png"))); // NOI18N
        pnlBackground.add(lblBPLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("GYM ADMINISTRATION ");
        pnlBackground.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        lblTitle2.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("SYSTEM");
        pnlBackground.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        lblDumbbellImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/dumbbellsmall.png"))); // NOI18N
        pnlBackground.add(lblDumbbellImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 40));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlBackground.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 30, -1, -1));

        getContentPane().add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Name: btnStaffActionPerformed
     * Purpose/description: to close the MemberType form and to create an object
     * of MemberRegistrationFormStaff to display MemberRegistrationFormStaff 
     * form.
     * @param evt - An event object represents the action of clicking on 
     * staff button.
     */
    private void btnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffActionPerformed
        this.setVisible(false);
        MemberRegistrationFormStaff staffForm = new MemberRegistrationFormStaff(this,memberOptions1);
        staffForm.setVisible(true);

    }//GEN-LAST:event_btnStaffActionPerformed

     /**
     * Name: btnStudentActionPerformed
     * Purpose/description: to close the MemberType form and to create an object
     * of MemberRegistrationFormStudent to display MemberRegistrationFormStudent 
     * form.
     * @param evt -An event object represents the action of clicking on 
     * student button.
     */
    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        this.setVisible(false);
        MemberRegistrationFormStudent studentForm = new MemberRegistrationFormStudent(this,memberOptions1);
        studentForm.setVisible(true);
    }//GEN-LAST:event_btnStudentActionPerformed

     /**
     * Name: btnBackActionPerformed
     * Purpose/description: to open MembersOptions form and close MemberType 
     * form.
     * @param evt - An event object represents the action of clicking on 
     * back button.
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        memberOptions1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnStaff;
    private javax.swing.JButton btnStudent;
    private javax.swing.JLabel lblBPLogo;
    private javax.swing.JLabel lblDumbbellImg;
    private javax.swing.JLabel lblMainMenuImg;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
