/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logic.*;

/**
 * Name:StaffMemberInformation class
 * @author Batool Isa, Fatima Mahfoodh, Fedaa Abdualwahab, Fatema Omran
 * @version 1.0
 * @created 15-Apr-2023 4:00 PM 
 * Purpose: Displaying the information of a staff member
 * It contains instances of the MembersOptions, Staff, and 
 * ViewPTMembersList classes for accessing and manipulating data related to staff members
 */

public class StaffMemberInformation extends javax.swing.JFrame {

    MembersOptions memberOptions4;
    Staff staff;
    ViewPTMembersList memberList;

    /**
     * Name:StaffMemberInformation
     * Purpose: It is a default constructor for the StaffMemberInformation class.
     * This constructor initializes the GUI components of the StaffMemberInformation object by calling the initComponents() method
     * Creates new form StaffMemberInformation
     */
    
    public StaffMemberInformation() {
        initComponents();

    }
     /**
      * Name:StaffMemberInformation
     * Purpose: Creates a new StaffMemberInformation object with the specified MembersOptions and Staff instances
     * This constructor initializes the MembersOptions and Staff members of the StaffMemberInformation object
     * and initializes the GUI components
     * @param memberOptions4 is the MembersOptions instance for accessing options related to members
     * @param staff is the Staff instance for accessing and manipulating data related to staff members
     */
    public StaffMemberInformation(MembersOptions memberOptions4, Staff staff) {
        this.memberOptions4 = memberOptions4;
        this.staff = staff;
        initComponents();

    }

     /**
     * Name:StaffMemberInformation
      * Purpose:Constructs a new StaffMemberInformation object with the specified ViewPTMembersList and Staff instances.
     * The constructor initializes the ViewPTMembersList and Staff members of the StaffMemberInformation object and initializes the GUI components
     * @param memberList is the ViewPTMembersList instance for displaying a list of staff members
     * @param staff is the Staff instance for accessing and manipulating data related to staff members
     */
    public StaffMemberInformation(ViewPTMembersList memberList, Staff staff) {
        this.memberList = memberList;
        this.staff = staff;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMemberID = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        memImg = new javax.swing.JLabel();
        lblMemIDOutput = new javax.swing.JLabel();
        lblFnameOutput = new javax.swing.JLabel();
        lblSurnameOutput = new javax.swing.JLabel();
        lblAddOutput = new javax.swing.JLabel();
        lblDOBOutput = new javax.swing.JLabel();
        lblPhoneOutput = new javax.swing.JLabel();
        lblGenderOutput = new javax.swing.JLabel();
        lblPositionOutput = new javax.swing.JLabel();
        lblDepNameOutput = new javax.swing.JLabel();
        lblPTid = new javax.swing.JLabel();
        lblPTOutPut = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBPLogo = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblDumbbellImg = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(57, 72, 103));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(248, 248, 248));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        lblMemberID.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblMemberID.setText("Member Id :");

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblFirstName.setText("First Name :");

        lblSurname.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblSurname.setText("Surname :");

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblAddress.setText("Address :");

        lblDOB.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblDOB.setText("Date of birth :");

        lblPhone.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblPhone.setText("Phone :");

        lblGender.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblGender.setText("Gender :");

        lblPosition.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblPosition.setText("Position :");

        lblDepartment.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblDepartment.setText("Department :");

        memImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/user.png"))); // NOI18N

        lblMemIDOutput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblFnameOutput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblSurnameOutput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblAddOutput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblDOBOutput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblPhoneOutput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblGenderOutput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblPositionOutput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblDepNameOutput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblPTid.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblPTid.setText("Personal Trainer ID:");

        lblPTOutPut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Staff");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(lblAddOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(memImg))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jLabel2)))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDepartment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDepNameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPositionOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPTid, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(lblPTOutPut, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSurnameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFnameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMemIDOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDOBOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(lblPhoneOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblGenderOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMemberID)
                                .addGap(18, 18, 18)
                                .addComponent(lblFirstName))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMemIDOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFnameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSurnameOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAddress)
                            .addComponent(lblAddOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDOB)
                            .addComponent(lblDOBOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPhone)
                                .addGap(18, 18, 18)
                                .addComponent(lblGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPhoneOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblGenderOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPosition)
                                    .addComponent(lblPositionOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDepartment)
                            .addComponent(lblDepNameOutput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPTid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPTOutPut, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(memImg)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 860, 460));

        lblBPLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/BPLogosmall.png"))); // NOI18N
        jPanel1.add(lblBPLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("GYM ADMINISTRATION ");
        jPanel1.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        lblTitle2.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("SYSTEM");
        jPanel1.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        lblDumbbellImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/dumbbellsmall.png"))); // NOI18N
        jPanel1.add(lblDumbbellImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 40));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     /**
     * Name:formWindowOpened
      * Purpose:Display staff member information by calling various methods of the Staff class
     * And if the staff member has a personal trainer the ID of the personal trainer will be displayed
     * @param evt the form Window opened Event object passed to the method
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblMemIDOutput.setText(Integer.toString(staff.getMembershipID()));
        lblFnameOutput.setText(staff.getFirstName());
        lblSurnameOutput.setText(staff.getSurname());
        lblAddOutput.setText(staff.getAddress());
        lblDOBOutput.setText(staff.getDateOfBirth());
        lblPhoneOutput.setText(Integer.toString(staff.getPhone()));
        lblGenderOutput.setText(staff.getGender());
        lblPositionOutput.setText(staff.getStaffPosition());
        lblDepNameOutput.setText(staff.getStaffDepartment());

        if (staff.isHasPt() == true) {
            lblPTOutPut.setText(Integer.toString(staff.getPtID()));
        } else {
            lblPTOutPut.setText("none");

        }

    }//GEN-LAST:event_formWindowOpened

     /**
     * Name:btnBackActionPerformed
     * Purpose:When it is clicked it sets the visibility of the MembersOptions window to true and
     * hide StaffMemberInformation window 
     * @param evt is the action event object that is passed to the method
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        memberOptions4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffMemberInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffMemberInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffMemberInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffMemberInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffMemberInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAddOutput;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBPLogo;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOBOutput;
    private javax.swing.JLabel lblDepNameOutput;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDumbbellImg;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFnameOutput;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGenderOutput;
    private javax.swing.JLabel lblMemIDOutput;
    private javax.swing.JLabel lblMemberID;
    private javax.swing.JLabel lblPTOutPut;
    private javax.swing.JLabel lblPTid;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneOutput;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblPositionOutput;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblSurnameOutput;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel memImg;
    // End of variables declaration//GEN-END:variables
}
