/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import Logic.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * @author Batool Isa, Fatima Mahfoodh, Fedaa Abdualwahab, Fatema Omran
 * @version 1.0
 * @created 10-May-2023 11:34:54 AM
 */

public class UpdateMemberInformationStudent extends javax.swing.JFrame {

    MembersOptions membersOptions;
    Student student;

     /**
     * Name: UpdateMemberInformationStudent
     * Purpose/description: custom constructors that used
     * to initialize an object using value passed as arguments.
     * It provides the functionality to edit the information of a member and save the changes in the system. 
     * It initializes the GUI components of the screen.

     * 
     * @param membersOptions - MembersOptions object 
     * @param student - student member object that represents the student object whose information is being updated.
     */
    public UpdateMemberInformationStudent(MembersOptions membersOptions, Student student) {
        this.student = student;
        this.membersOptions = membersOptions;
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);

    }
    
    
     /**
     * Name: UpdateMemberInformationStudent
     * Purpose/description: default constructors that
     * used to initialize the form components.
     * It initializes the GUI components of the screen.
     */
    public UpdateMemberInformationStudent() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupGenderStudentMRF = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnUStudentMRFSave = new javax.swing.JButton();
        lblUStudentMRFStudent = new javax.swing.JLabel();
        lblUStudentMRFTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblUStudentMRFFirstName = new javax.swing.JLabel();
        txtUStudentMRFFirstName = new javax.swing.JTextField();
        lblStudentMRFPhone = new javax.swing.JLabel();
        txtUStudentMRFPhone = new javax.swing.JTextField();
        lblUStudentMRFDeptNo = new javax.swing.JLabel();
        txtUStudentMRFTeam = new javax.swing.JTextField();
        lblUStudentMRFGender = new javax.swing.JLabel();
        btnUStudentMRFMale = new javax.swing.JRadioButton();
        btnUStudentMRFFemale = new javax.swing.JRadioButton();
        lblFnameError = new javax.swing.JLabel();
        lblPhoneError = new javax.swing.JLabel();
        lblTeamError = new javax.swing.JLabel();
        lblFnameError1 = new javax.swing.JLabel();
        lblPhoneError1 = new javax.swing.JLabel();
        lblTeamError1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblUStudentMRFSurname = new javax.swing.JLabel();
        txtUStudentMRFSurname = new javax.swing.JTextField();
        lblUStudentMRFAddress = new javax.swing.JLabel();
        txtUStudentMRFAddress = new javax.swing.JTextField();
        lblUStudentMRFDOB = new javax.swing.JLabel();
        jDateChooserUStudentMRF = new com.toedter.calendar.JDateChooser();
        lblUStudentMRFPosition = new javax.swing.JLabel();
        jComboBoxUStudentMRF = new javax.swing.JComboBox<>();
        lblLnameError = new javax.swing.JLabel();
        lblAddressError = new javax.swing.JLabel();
        lblDateError = new javax.swing.JLabel();
        lblBPLogo = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblDumbbellImg = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(57, 72, 103));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUStudentMRFSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUStudentMRFSave.setText("Save");
        btnUStudentMRFSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUStudentMRFSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnUStudentMRFSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, -1, -1));

        lblUStudentMRFStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUStudentMRFStudent.setForeground(new java.awt.Color(179, 190, 194));
        lblUStudentMRFStudent.setText("STUDENT");
        jPanel1.add(lblUStudentMRFStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, -1, -1));

        lblUStudentMRFTitle.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblUStudentMRFTitle.setForeground(new java.awt.Color(156, 176, 219));
        lblUStudentMRFTitle.setText("Update Member Information");
        jPanel1.add(lblUStudentMRFTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jPanel2.setBackground(new java.awt.Color(57, 72, 103));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUStudentMRFFirstName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUStudentMRFFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblUStudentMRFFirstName.setText("First Name:");
        jPanel2.add(lblUStudentMRFFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));
        jPanel2.add(txtUStudentMRFFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 160, 30));

        lblStudentMRFPhone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStudentMRFPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentMRFPhone.setText("Phone:");
        jPanel2.add(lblStudentMRFPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 80, 30));
        jPanel2.add(txtUStudentMRFPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 160, 30));

        lblUStudentMRFDeptNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUStudentMRFDeptNo.setForeground(new java.awt.Color(255, 255, 255));
        lblUStudentMRFDeptNo.setText("Team:");
        jPanel2.add(lblUStudentMRFDeptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));
        jPanel2.add(txtUStudentMRFTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 160, 30));

        lblUStudentMRFGender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUStudentMRFGender.setForeground(new java.awt.Color(255, 255, 255));
        lblUStudentMRFGender.setText("Gender:");
        jPanel2.add(lblUStudentMRFGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        GroupGenderStudentMRF.add(btnUStudentMRFMale);
        btnUStudentMRFMale.setForeground(new java.awt.Color(255, 255, 255));
        btnUStudentMRFMale.setText("Male");
        jPanel2.add(btnUStudentMRFMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 98, 20));

        GroupGenderStudentMRF.add(btnUStudentMRFFemale);
        btnUStudentMRFFemale.setForeground(new java.awt.Color(255, 255, 255));
        btnUStudentMRFFemale.setText("Female");
        jPanel2.add(btnUStudentMRFFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 98, -1));

        lblFnameError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblFnameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 230, 30));

        lblPhoneError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblPhoneError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 250, 30));

        lblTeamError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblTeamError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 340, 30));

        lblFnameError1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblFnameError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 230, 30));

        lblPhoneError1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblPhoneError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 250, 30));

        lblTeamError1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblTeamError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 340, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 370, 250));

        jPanel3.setBackground(new java.awt.Color(57, 72, 103));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUStudentMRFSurname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUStudentMRFSurname.setForeground(new java.awt.Color(255, 255, 255));
        lblUStudentMRFSurname.setText("Surname:");
        jPanel3.add(lblUStudentMRFSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel3.add(txtUStudentMRFSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 160, 30));

        lblUStudentMRFAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUStudentMRFAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblUStudentMRFAddress.setText("Address:");
        jPanel3.add(lblUStudentMRFAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, -1));
        jPanel3.add(txtUStudentMRFAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 160, 30));

        lblUStudentMRFDOB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUStudentMRFDOB.setForeground(new java.awt.Color(255, 255, 255));
        lblUStudentMRFDOB.setText("Date of birth:");
        jPanel3.add(lblUStudentMRFDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));
        jPanel3.add(jDateChooserUStudentMRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 160, 30));

        lblUStudentMRFPosition.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUStudentMRFPosition.setForeground(new java.awt.Color(255, 255, 255));
        lblUStudentMRFPosition.setText("Major:");
        jPanel3.add(lblUStudentMRFPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 68, -1));

        jComboBoxUStudentMRF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxUStudentMRF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT", "Logistics", "Business", "Web media", "Engineering", "Visual design", "Digital marketing", "Film & Animation" }));
        jPanel3.add(jComboBoxUStudentMRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 160, 30));

        lblLnameError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblLnameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 230, 30));

        lblAddressError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblAddressError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 250, 30));

        lblDateError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblDateError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 500, 250));

        lblBPLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/BPLogosmall.png"))); // NOI18N
        jPanel1.add(lblBPLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("GYM ADMINISTRATION ");
        jPanel1.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        lblTitle2.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("SYSTEM");
        jPanel1.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        lblDumbbellImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/dumbbellsmall.png"))); // NOI18N
        jPanel1.add(lblDumbbellImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 40));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 646));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Name:btnUStudentMRFSaveActionPerformed
     * Purpose/description: This method is called when the "Save" button is clicked. 
     * It validates the user input for the student member information fields,.
     * If the input is valid, it updates the information of the selected student member in the system.
     * If the input is invalid, it displays error messages to the user. 
     * 
     * @param evt the event that triggered the invocation of this method.
     * @exception NumberFormatException 
     */
    private void btnUStudentMRFSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUStudentMRFSaveActionPerformed
        lblFnameError.setText(null);
        lblLnameError.setText(null);
        lblAddressError.setText(null);
        lblTeamError.setText(null);
        lblPhoneError.setText(null);
        lblDateError.setText(null);

        boolean submit = true;

        if (txtUStudentMRFFirstName.getText().isEmpty() || txtUStudentMRFFirstName.getText().length() < 3) {
            lblFnameError.setText("*First name must be at least 3 characters");
            submit = false;
        }
        if (txtUStudentMRFSurname.getText().isEmpty() || txtUStudentMRFSurname.getText().length() < 3) {
            lblLnameError.setText("*Surname must be at least 3 characters");
            submit = false;
        }
        if (txtUStudentMRFAddress.getText().isEmpty() || txtUStudentMRFAddress.getText().length() < 6) {
            lblAddressError.setText("*Address must be at least 6 characters");
            submit = false;
        }
        if (txtUStudentMRFTeam.getText().isEmpty() || txtUStudentMRFTeam.getText().length() < 5) {
            lblTeamError.setText("*Department Name must be at least 5 characters");
            submit = false;
        }
        if (jDateChooserUStudentMRF.getDate() == null) {
            lblDateError.setText("*Date of Birth cannot be null");
            submit = false;
        }
        if (txtUStudentMRFPhone.getText().isEmpty() || txtUStudentMRFPhone.getText().length() < 6) {
            lblPhoneError.setText("*Phone must be at least 6 digits");
            submit = false;
        }
        try {
            if (submit == true) {
                String fName = txtUStudentMRFFirstName.getText();
                String lName = txtUStudentMRFSurname.getText();
                String address = txtUStudentMRFAddress.getText();
                String team = txtUStudentMRFTeam.getText();
                String major = (String) jComboBoxUStudentMRF.getSelectedItem();
                SimpleDateFormat sdf = new SimpleDateFormat("d/M/yyyy");
                String dateOfBirth = sdf.format(jDateChooserUStudentMRF.getDate());
                int phone = Integer.parseInt(txtUStudentMRFPhone.getText());
                String gender;
                if (btnUStudentMRFMale.isSelected()) {
                    gender = "Male";
                } else {
                    gender = "Female";
                }
                GymSystem.alterStduentMember(student.getMembershipID(), fName, lName, address, dateOfBirth, phone, gender, team, major);
                JOptionPane.showMessageDialog(this, "The Member information has been updated", "Information Updated", 1);
                membersOptions.setVisible(true);
            }
        } catch (NumberFormatException ex1) {
            JOptionPane.showMessageDialog(this, "Phone Input must be number", "Number Format Exception", 0);
        }
    }//GEN-LAST:event_btnUStudentMRFSaveActionPerformed

     /** 
     * Name:formWindowOpened
     * Invoked when UpdateMemberInformationStaff form is opened.
     * It sets the text of the student information fields to the current information of the selected student member,
     * which is passed as an object to the constructor of this screen.
     * 
     * @param evt the event that triggered the invocation of this method (WindowEvent).
     */

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            txtUStudentMRFFirstName.setText(student.getFirstName());
            txtUStudentMRFSurname.setText(student.getSurname());
            txtUStudentMRFAddress.setText(student.getAddress());
            txtUStudentMRFTeam.setText(student.getStudentTeam());
            jComboBoxUStudentMRF.setSelectedItem(student.getStudentMajor());
            txtUStudentMRFPhone.setText(Integer.toString(student.getPhone()));

            String dobString = student.getDateOfBirth();
            Date date = new SimpleDateFormat("d/M/yyyy").parse(dobString);
            jDateChooserUStudentMRF.setDate(date);

            if (student.getGender().equalsIgnoreCase("male")) {
                btnUStudentMRFMale.setSelected(true);
            } else if (student.getGender().equalsIgnoreCase("female")) {
                btnUStudentMRFFemale.setSelected(true);
            }
        } catch (ParseException ex) {
            Logger.getLogger(UpdateMemberInformationStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

     /** 
     * Name:btnBackActionPerformed
     * Purpose/description: This method is called when the "Back" button is clicked.
     * It sets the visibility of the current screen to false and the visibility of the member options screen to true.
     * 
     * @param evt the event that triggered the invocation of this method (ActionEvent).
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        membersOptions.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMemberInformationStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMemberInformationStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMemberInformationStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMemberInformationStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMemberInformationStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupGenderStudentMRF;
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnUStudentMRFFemale;
    private javax.swing.JRadioButton btnUStudentMRFMale;
    private javax.swing.JButton btnUStudentMRFSave;
    private javax.swing.JComboBox<String> jComboBoxUStudentMRF;
    private com.toedter.calendar.JDateChooser jDateChooserUStudentMRF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAddressError;
    private javax.swing.JLabel lblBPLogo;
    private javax.swing.JLabel lblDateError;
    private javax.swing.JLabel lblDumbbellImg;
    private javax.swing.JLabel lblFnameError;
    private javax.swing.JLabel lblFnameError1;
    private javax.swing.JLabel lblLnameError;
    private javax.swing.JLabel lblPhoneError;
    private javax.swing.JLabel lblPhoneError1;
    private javax.swing.JLabel lblStudentMRFPhone;
    private javax.swing.JLabel lblTeamError;
    private javax.swing.JLabel lblTeamError1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblUStudentMRFAddress;
    private javax.swing.JLabel lblUStudentMRFDOB;
    private javax.swing.JLabel lblUStudentMRFDeptNo;
    private javax.swing.JLabel lblUStudentMRFFirstName;
    private javax.swing.JLabel lblUStudentMRFGender;
    private javax.swing.JLabel lblUStudentMRFPosition;
    private javax.swing.JLabel lblUStudentMRFStudent;
    private javax.swing.JLabel lblUStudentMRFSurname;
    private javax.swing.JLabel lblUStudentMRFTitle;
    private javax.swing.JTextField txtUStudentMRFAddress;
    private javax.swing.JTextField txtUStudentMRFFirstName;
    private javax.swing.JTextField txtUStudentMRFPhone;
    private javax.swing.JTextField txtUStudentMRFSurname;
    private javax.swing.JTextField txtUStudentMRFTeam;
    // End of variables declaration//GEN-END:variables
}
