/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import Logic.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * @author Batool Isa, Fatima Mahfoodh, Fedaa Abdualwahab, Fatema Omran
 * @version 1.0
 * @created 10-May-2023 11:34:54 AM
 */

public class UpdateMemberInformationStaff extends javax.swing.JFrame {

    MembersOptions membersOptions;
    Staff staff;

     /**
     * Name: UpdateMemberInformationStaff
     * Purpose/description: custom constructors that used
     * to initialize an object using value passed as arguments.
     * It provides the functionality to edit the information of a member and save the changes in the system. 
     * It initializes the GUI components of the screen.
     * 
     * @param membersOptions - MembersOptions object 
     * @param staff - staff member object that represents the staff object whose information is being updated.
     */
    public UpdateMemberInformationStaff(MembersOptions membersOptions, Staff staff) {
        this.staff = staff;
        this.membersOptions = membersOptions;
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }
    
    /**
     * Name: UpdateMemberInformationStaff
     * Purpose/description: default constructors that
     * used to initialize the form components.
     * It initializes the GUI components of the screen.
     */
    public UpdateMemberInformationStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupGenderUMS = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblUMStaff = new javax.swing.JLabel();
        btnUMSSave = new javax.swing.JButton();
        lblUMSTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblUMSFirstName = new javax.swing.JLabel();
        txtUMSFirstName = new javax.swing.JTextField();
        lblUMSPhone = new javax.swing.JLabel();
        txtUMSPhone = new javax.swing.JTextField();
        lblUMSDeptNo = new javax.swing.JLabel();
        txtUMSDeptName = new javax.swing.JTextField();
        lblUMSGender = new javax.swing.JLabel();
        btnUMSMale = new javax.swing.JRadioButton();
        btnUMSFemale = new javax.swing.JRadioButton();
        lblFnameError = new javax.swing.JLabel();
        lblPhoneError = new javax.swing.JLabel();
        lblDepError = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblUMSSurname = new javax.swing.JLabel();
        txtUMSSurname = new javax.swing.JTextField();
        lblUMSAddress = new javax.swing.JLabel();
        txtUMSAddress = new javax.swing.JTextField();
        lblUMSDOB = new javax.swing.JLabel();
        jDateChooserUMS = new com.toedter.calendar.JDateChooser();
        lblUMSPosition = new javax.swing.JLabel();
        txtUMSPosition = new javax.swing.JTextField();
        lblLnameError = new javax.swing.JLabel();
        lblAddressError = new javax.swing.JLabel();
        lblDateError = new javax.swing.JLabel();
        lblPostitionError = new javax.swing.JLabel();
        lblBPLogo = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblDumbbellImg = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(57, 72, 103));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUMStaff.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUMStaff.setForeground(new java.awt.Color(179, 190, 194));
        lblUMStaff.setText("STAFF");
        jPanel1.add(lblUMStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, -1, -1));

        btnUMSSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUMSSave.setText("Save");
        btnUMSSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUMSSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnUMSSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, -1, -1));

        lblUMSTitle.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblUMSTitle.setForeground(new java.awt.Color(156, 176, 219));
        lblUMSTitle.setText("Update Member Information");
        jPanel1.add(lblUMSTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jPanel2.setBackground(new java.awt.Color(57, 72, 103));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUMSFirstName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUMSFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblUMSFirstName.setText("First Name:");
        jPanel2.add(lblUMSFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 120, -1));
        jPanel2.add(txtUMSFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 160, 30));

        lblUMSPhone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUMSPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblUMSPhone.setText("Phone:");
        jPanel2.add(lblUMSPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 100, -1));
        jPanel2.add(txtUMSPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 160, 30));

        lblUMSDeptNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUMSDeptNo.setForeground(new java.awt.Color(255, 255, 255));
        lblUMSDeptNo.setText("Department Name:");
        jPanel2.add(lblUMSDeptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));
        jPanel2.add(txtUMSDeptName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 160, 30));

        lblUMSGender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUMSGender.setForeground(new java.awt.Color(255, 255, 255));
        lblUMSGender.setText("Gender:");
        jPanel2.add(lblUMSGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        GroupGenderUMS.add(btnUMSMale);
        btnUMSMale.setForeground(new java.awt.Color(255, 255, 255));
        btnUMSMale.setText("Male");
        jPanel2.add(btnUMSMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 98, 20));

        GroupGenderUMS.add(btnUMSFemale);
        btnUMSFemale.setForeground(new java.awt.Color(255, 255, 255));
        btnUMSFemale.setText("Female");
        jPanel2.add(btnUMSFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 98, -1));

        lblFnameError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblFnameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 230, 30));

        lblPhoneError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblPhoneError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 30));

        lblDepError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(lblDepError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 400, 310));

        jPanel3.setBackground(new java.awt.Color(57, 72, 103));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUMSSurname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUMSSurname.setForeground(new java.awt.Color(255, 255, 255));
        lblUMSSurname.setText("Surname:");
        jPanel3.add(lblUMSSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel3.add(txtUMSSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 160, 30));

        lblUMSAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUMSAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblUMSAddress.setText("Address:");
        jPanel3.add(lblUMSAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, -1));
        jPanel3.add(txtUMSAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 160, 30));

        lblUMSDOB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUMSDOB.setForeground(new java.awt.Color(255, 255, 255));
        lblUMSDOB.setText("Date of birth:");
        jPanel3.add(lblUMSDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 140, -1));
        jPanel3.add(jDateChooserUMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 160, 30));

        lblUMSPosition.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUMSPosition.setForeground(new java.awt.Color(255, 255, 255));
        lblUMSPosition.setText("Position:");
        jPanel3.add(lblUMSPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 90, -1));

        txtUMSPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUMSPositionActionPerformed(evt);
            }
        });
        jPanel3.add(txtUMSPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, 30));

        lblLnameError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblLnameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 230, 30));

        lblAddressError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblAddressError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 250, 30));

        lblDateError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblDateError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 30));

        lblPostitionError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblPostitionError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, -1, 270));

        lblBPLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/BPLogosmall.png"))); // NOI18N
        jPanel1.add(lblBPLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("GYM ADMINISTRATION ");
        jPanel1.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        lblTitle2.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("SYSTEM");
        jPanel1.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        lblDumbbellImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/dumbbellsmall.png"))); // NOI18N
        jPanel1.add(lblDumbbellImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 40));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUMSPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUMSPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUMSPositionActionPerformed

     /**
     * Name:btnUMSSaveActionPerformed
     * Purpose/description: This method is called when the "Save" button is clicked in the UpdateMemberInformationStaff form . 
     * It validates the user input for the staff member information fields,.
     * If the input is valid, it updates the information of the selected staff member in the system.
     * If the input is invalid, it displays error messages to the user. 
     * 
     * @param evt the event that triggered the invocation of this method.
     */
    private void btnUMSSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUMSSaveActionPerformed
        lblFnameError.setText(null);
        lblLnameError.setText(null);
        lblAddressError.setText(null);
        lblDepError.setText(null);
        lblPostitionError.setText(null);
        lblPhoneError.setText(null);
        lblDateError.setText(null);
        
        boolean save = true;

        if (txtUMSFirstName.getText().isEmpty() || txtUMSFirstName.getText().length() < 3) {
            lblFnameError.setText("*First name must be at least 3 characters");
            save = false;
        }
        if (txtUMSSurname.getText().isEmpty() || txtUMSSurname.getText().length() < 3) {
            lblLnameError.setText("*Surname must be at least 3 characters");
            save = false;
        }
        if (txtUMSAddress.getText().isEmpty() || txtUMSAddress.getText().length() < 6) {
            lblAddressError.setText("*Address must be at least 6 characters");
            save = false;
        }
        if (txtUMSDeptName.getText().isEmpty() || txtUMSDeptName.getText().length() < 5) {
            lblDepError.setText("*Department Name must be at least 5 characters");
            save = false;
        }
        if (txtUMSPosition.getText().isEmpty() || txtUMSPosition.getText().length() < 5) {
            lblPostitionError.setText("*Position must be at least 5 characters");
            save = false;
        }
        if (jDateChooserUMS.getDate() == null) {
            lblDateError.setText("*Date of Birth cannot be null");
            save = false;
        }
        if (txtUMSPhone.getText().isEmpty() || txtUMSPhone.getText().length() < 6) {
            lblPhoneError.setText("*Phone must be at least 6 digits");
            save = false;
        }
        try {
            if (save == true) {
                String fName = txtUMSFirstName.getText();
                String lName = txtUMSSurname.getText();
                String address = txtUMSAddress.getText();
                String depName = txtUMSDeptName.getText();
                String position = txtUMSPosition.getText();
                SimpleDateFormat sdf = new SimpleDateFormat("d/M/yyyy");
                String dateOfBirth = sdf.format(jDateChooserUMS.getDate());
                int phone = Integer.parseInt(txtUMSPhone.getText());
                String gender;
                if (btnUMSMale.isSelected()) {
                    gender = "Male";
                } else {
                    gender = "Female";
                }
                GymSystem.alterStaffMember(staff.getMembershipID(), fName, lName, address, dateOfBirth, phone, gender, depName, position);
                JOptionPane.showMessageDialog(this, "The Member information has been updated", "Information Updated", 1);
                membersOptions.setVisible(true);
                //set Position code
            }
        } catch (NumberFormatException ex1) {
            JOptionPane.showMessageDialog(this, "Phone Input must be number", "Number Format Exception", 0);

        }
    }//GEN-LAST:event_btnUMSSaveActionPerformed

     /** 
     * Name:formWindowOpened
     * Invoked when UpdateMemberInformationStaff form is opened.
     * It sets the text of the staff information fields to the current information of the selected staff member,
     * which is passed as an object to the constructor of this screen.
     * 
     * @param evt the event that triggered the invocation of this method (WindowEvent).
     */

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            txtUMSFirstName.setText(staff.getFirstName());
            txtUMSSurname.setText(staff.getSurname());
            txtUMSAddress.setText(staff.getAddress());
            txtUMSDeptName.setText(staff.getStaffDepartment());
            txtUMSPosition.setText(staff.getStaffPosition());

            String dobString = staff.getDateOfBirth();
            Date date = new SimpleDateFormat("d/M/yyy").parse(dobString);
            jDateChooserUMS.setDate(date);

            txtUMSPhone.setText(Integer.toString(staff.getPhone()));

            if (staff.getGender().equalsIgnoreCase("male")) {
                btnUMSMale.setSelected(true);
            } else if (staff.getGender().equalsIgnoreCase("female")){
                btnUMSFemale.setSelected(true);
            }
        } catch (ParseException ex) {
            Logger.getLogger(UpdateMemberInformationStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

     /** 
     * Name:btnBackActionPerformed
     * Purpose/description: This method is called when the "Back" button is clicked.
     * It sets the visibility of the current screen to false and the visibility of the member options screen to true.
     * 
     * @param evt the event that triggered the invocation of this method (ActionEvent).
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        membersOptions.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMemberInformationStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMemberInformationStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMemberInformationStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMemberInformationStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMemberInformationStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupGenderUMS;
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnUMSFemale;
    private javax.swing.JRadioButton btnUMSMale;
    private javax.swing.JButton btnUMSSave;
    private com.toedter.calendar.JDateChooser jDateChooserUMS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAddressError;
    private javax.swing.JLabel lblBPLogo;
    private javax.swing.JLabel lblDateError;
    private javax.swing.JLabel lblDepError;
    private javax.swing.JLabel lblDumbbellImg;
    private javax.swing.JLabel lblFnameError;
    private javax.swing.JLabel lblLnameError;
    private javax.swing.JLabel lblPhoneError;
    private javax.swing.JLabel lblPostitionError;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblUMSAddress;
    private javax.swing.JLabel lblUMSDOB;
    private javax.swing.JLabel lblUMSDeptNo;
    private javax.swing.JLabel lblUMSFirstName;
    private javax.swing.JLabel lblUMSGender;
    private javax.swing.JLabel lblUMSPhone;
    private javax.swing.JLabel lblUMSPosition;
    private javax.swing.JLabel lblUMSSurname;
    private javax.swing.JLabel lblUMSTitle;
    private javax.swing.JLabel lblUMStaff;
    private javax.swing.JTextField txtUMSAddress;
    private javax.swing.JTextField txtUMSDeptName;
    private javax.swing.JTextField txtUMSFirstName;
    private javax.swing.JTextField txtUMSPhone;
    private javax.swing.JTextField txtUMSPosition;
    private javax.swing.JTextField txtUMSSurname;
    // End of variables declaration//GEN-END:variables
}
